# Generated by Django 4.2.26 on 2026-01-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_compromise_reason_user_compromised_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login_user_agent",
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
