# Generated by Django 4.2.26 on 2026-01-08 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apikeys", "0002_apikey_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SIGNUP_SUCCESS", "Signup success"),
                            ("SIGNUP_FAILED", "Signup failed"),
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("ACCOUNT_LOCKED", "Account Locked"),
                            ("API_KEY_CREATED", "API Key Created"),
                            ("API_KEY_CREATION_BLOCKED", "API Key Creation Blocked"),
                            ("API_KEY_REVOKED", "API Key Revoked"),
                            (
                                "API_KEY_REVOCATION_BLOCKED",
                                "API Key REVOCATION Blocked",
                            ),
                            ("API_KEY_AUTH_FAILED", "API Key Auth Failed"),
                            ("API_KEY_EXPIRED", "API Key Expired"),
                            ("SCOPE_VIOLATION", "Scope Violation"),
                            ("COMPROMISE_DETECTED", "Compromise Detected"),
                            ("REMEDIATION_APPLIED", "Remediation Applied"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=16,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to="apikeys.apikey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type"], name="security_se_event_t_e8f9c2_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="security_se_severit_9bbb1c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="security_se_created_841554_idx"
                    ),
                ],
            },
        ),
    ]
