# Generated by Django 4.2.26 on 2026-01-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SIGNUP_SUCCESS", "Signup success"),
                    ("SIGNUP_FAILED", "Signup failed"),
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("ACCOUNT_LOCKED", "Account Locked"),
                    ("ACCOUNT_UNLOCKED", "Account unLocked"),
                    ("API_KEY_CREATED", "API Key Created"),
                    ("API_KEY_CREATION_BLOCKED", "API Key Creation Blocked"),
                    ("API_KEY_REVOKED", "API Key Revoked"),
                    ("API_KEY_REVOCATION_BLOCKED", "API Key REVOCATION Blocked"),
                    ("API_KEY_AUTH_FAILED", "API Key Auth Failed"),
                    ("API_KEY_EXPIRED", "API Key Expired"),
                    ("SCOPE_VIOLATION", "Scope Violation"),
                    ("COMPROMISE_DETECTED", "Compromise Detected"),
                    ("REMEDIATION_APPLIED", "Remediation Applied"),
                ],
                max_length=64,
            ),
        ),
    ]
