# Generated by Django 4.2.26 on 2026-01-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("signup_success", "Signup success"),
                    ("login_success", "Login success"),
                    ("account_locked", "Account locked"),
                    ("account_unlocked", "Account unlocked"),
                    ("account_compromised", "Account compromised"),
                    ("compromise_cleared", "Compromise cleared"),
                    ("api_key_created", "API key created"),
                    ("api_key_used", "API key used"),
                    ("api_key_denied", "API key denied"),
                    ("api_key_revoked", "API key revoked"),
                    ("all_api_keys_revoked", "All API keys revoked"),
                    ("api_key_rate_limited", "API key rate limited"),
                ],
                max_length=50,
            ),
        ),
    ]
