# Generated by Django 4.2.26 on 2026-01-05 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name to identify this key (e.g. 'CI pipeline').",
                        max_length=100,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        help_text="Hash of the API key. Raw key is never stored.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        default=list, help_text="List of permitted scopes for this key."
                    ),
                ),
                (
                    "is_revoked",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether this key has been revoked.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
