# Generated by Django 4.2.26 on 2026-01-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apikeys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
